version: '3.7'

services:
  js_store_backend:
    build: ./
    container_name: js_store_backend
    ports:
      - 4040:4040
    environment:
      - CONFIG_DATABASE_HOST=js_store_backend
      - CONFIG_DATABASE_PORT=5432
      - CONFIG_DATABASE_DATABASE=js_store
      - CONFIG_DATABASE_USERNAME=js_store
      - CONFIG_DATABASE_PASSWORD=js_store
    depends_on:
      - js_store_database
    links:
      - js_store_database
    restart: 'no'

  js_store_database:
    image: postgres:12.3
    container_name: js_store_database
    ports:
      - 4041:5432
    environment:
      - POSTGRES_DB=js_store
      - POSTGRES_USER=js_store
      - POSTGRES_PASSWORD=js_store
    volumes:
      - postgres-js_store:/var/lib/postgresql/data
    restart: 'no'

volumes:
  postgres-js_store:
